apiVersion: v1
kind: Secret
metadata:
  name: mysql-cluster-backup-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin123
  AWS_REGION: us-east-1
  S3_PROVIDER: Other
  S3_ENDPOINT: http://minio.minio.svc.cluster.local:9000
  AWS_STORAGE_CLASS: STANDARD
