apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # root password is required to be specified
  ROOT_PASSWORD: cGFzc3dvcmQ=
  # a user name to be created, not required
  USER: YmFnaXN0b191c2Vy
  # a password for user, not required
  PASSWORD: cGFzc3dvcmQ=
  # a name for database that will be created, not required
  DATABASE: YmFnaXN0b19kYg==